pipeline { 
    agent any 
    stages {
        stage('--clean') { 
            steps { 
                sh 'mvn clean' 
            }
        }
        stage('--test--'){
            steps {
                sh 'mvn test'
            }
        }
        stage('--package--') {
            steps {
                def mvnHome = tool name: 'maven3.6', type: 'maven'
                sh '$(mvnHome)/bin/mvn package'
            }
        }
    }
}
