Jenkinsfile (Declarative Pipeline)
pipeline { 
    agent any 
    stages {
        stage('--clean') { 
            steps { 
                sh 'mvn clean' 
            }
        }
        stage('--test--'){
            steps {
                sh 'mvn test'
                junit 'reports/**/*.xml' 
            }
        }
        stage('--package--') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
